allowBuilds:
  cpu-features: false
  msgpackr-extract: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
  ssh2: false
catalog:
  "@commitlint/cli": ^21.2.1
  "@commitlint/config-conventional": ^21.2.0
  "@commitlint/types": ^21.2.0
  "@effect/platform-node": ^4.0.0-rc.112
  "@effect/platform-node-shared": ^4.0.0-rc.112
  "@effect/vitest": ^4.0.0-rc.112
  "@loaderkit/resolve": ^1.0.2
  "@systemfsoftware/all": ^1.1.3
  "@systemfsoftware/arethetypeswrong-cli": ^4.0.0
  "@systemfsoftware/effect-gherkin-spec": ^4.0.1
  "@systemfsoftware/effect-memfs": ^1.3.4
  "@systemfsoftware/effect-schema-law": ^2.0.2
  "@systemfsoftware/effect-schema-vite": ^2.0.3
  "@systemfsoftware/npm-package": ^0.2.2
  "@systemfsoftware/oxlint-plugin-effect-dmmf": ^5.3.0
  "@systemfsoftware/stryker-js-cli": ^6.0.0
  "@systemfsoftware/stryker-js-typescript-checker": ^5.0.0
  "@systemfsoftware/stryker-js-vitest-runner": ^4.0.0
  "@systemfsoftware/stryker-plugins": ^3.0.0
  "@systemfsoftware/stryker-test-contribution": ^2.0.0
  "@systemfsoftware/tsconfig": ^1.3.3
  "@types/node": ^24
  "@types/semver": ^7.5.0
  "@types/validate-npm-package-name": ^4.0.0
  "@vitest/coverage-v8": ^4
  "@vitest/snapshot": ^4
  cjs-module-lexer: ^2.2.1
  effect: ^4.0.0-rc.112
  fast-check: ^4
  husky: ^9.1.7
  lint-staged: ^17.1.0
  oxlint: ^1.77.0
  oxlint-tsgolint: 7.0.2001
  rimraf: ^6.1.3
  semver: ^7.5.4
  testcontainers: ^12.1.0
  tsdown: ^0.23.0
  turbo: ^2.10.12
  typescript: ^7
  validate-npm-package-name: ^8.0.0
  vite-tsconfig-paths: ^6.1.1
  vitest: ^4
catalogMode: prefer
catalogs:
  attw:
    typescript: ^6.0.3
packages:
  - apps/*
  - packages/*
  - packages/arethetypeswrong/*
